# Build Script
# Generated by mkproj ($mkproj_version).

pushd "$(dirname "$0")"

# Load Config
source .build

# Define Flags

if [ $build_type == Debug ]; then
    flags+=$debug_flags
else
    flags+=$release_flags
fi    

flags+=" -D${macro_prefix}VERSION_MAJOR=$version_major"
flags+=" -D${macro_prefix}VERSION_MINOR=$version_minor"
flags+=" -D${macro_prefix}VERSION_BUILD=$version_build"

# Build Target
$compiler $sources $flags -o $target

# Update version_build
((version_build++))
sed -i ".backup" "s/version_build=[0-9]*/version_build=$version_build/" .build
rm -f .build.backup

popd
